auto: true
url: "https://google.github.io"
baseurl: '/dagger'
markdown: kramdown
dagger:
  groupId: com.google.dagger
  version: 2.2

plugins:
  - jekyll-remote-theme
  
remote_theme: alexcarpenter/material-jekyll-theme
sha: d99ac3a830b15c99a636a6f59818ecc2a0d6f7d6
