auto: true
url: "https://google.github.io"
baseurl: '/dagger'
markdown: kramdown
dagger:
  groupId: com.google.dagger
  version: 2.2
repository: google/dagger

title: Your awesome title
email: your-email@domain.com
description:
  DO NOT SUBMIT
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Social
githubUsername:
twitterUsername:
dribbbleUsername:
codepenUsername:

themeColor: orange
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

nav:
  - item:
      name: Home
      url: /
  - item:
      name: "User's Guide"
      url: /users-guide
  - item:
      name: Android
      url: /android
  - item:
      name: Multibindings
      url: /multibindings
  - item:
      name: Subcomponents
      url: /subcomponents
  - item:
      name: Producers
      url: /producers
  - item:
      name: Testing
      url: /testing
  - item:
      name: Dagger 1 Migration
      url: /dagger-1-migration
  - item:
      name: Resources
      url: /Resources
  - item:
      name: FAQ
      url: /faq
